### PR TITLE
Create kruskal.cpp

### PR DESCRIPTION
**Pull request by PoojithaR**
Resolves Issue #175

### Description
 C++ program implementing Kruskal's algorithm.

### CODE REVIEW

**Review by archana98priya — CHANGES_REQUESTED** [review]
change the file name to  your_name.cpp

**Comment by PoojithaR** [comment]
the filename has extension as .cpp itself!!

**Review by archana98priya — COMMENTED** [review]
change the file name to poojithar.cpp

**Comment by PoojithaR** [comment]
i claim !! i'll be using python language!!

**Comment by PoojithaR** [comment]
i claim!!

**Pull request merged**
